// <auto-generated />
using System;
using B_Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B_Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240418204959_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("D_Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardineriay Bricolaje"
                        });
                });

            modelBuilder.Entity("D_Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("106f1c8b-7db0-4544-81cc-d7d3781164ca"),
                            Category = 1,
                            Description = "Heladera con freezer Marca Dream Hdr280f00b blanca clase A",
                            Discount = 17,
                            Name = "Heladera con freezer",
                            Price = 632798m
                        },
                        new
                        {
                            ProductId = new Guid("93f16da6-b694-4816-ac62-b4e2be7f7052"),
                            Category = 1,
                            Description = "Aire acondicionado split frio/calor Carrier XPower 5120W 4400F 53HVG1801E",
                            Discount = 0,
                            Name = "Aire acondicionado",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("1138ca5c-9bdf-47ca-9ee4-c3217b746b93"),
                            Category = 1,
                            Description = "Smart TV 32 pulgadas HD Android TV Admiral AD32E3A",
                            Discount = 30,
                            Name = "Smart TV",
                            Price = 199999m
                        },
                        new
                        {
                            ProductId = new Guid("ca69a1e6-1ca7-41b4-b544-0d835d0eebb2"),
                            Category = 1,
                            Description = "Lavaropas carga frontal 6kg 800 RPM Drean Next 6.08 ECO",
                            Discount = 24,
                            Name = "Lavaropas Carga Frontal",
                            Price = 669999m
                        },
                        new
                        {
                            ProductId = new Guid("acf8c593-e5e2-41c8-8f53-b8c717ef16d2"),
                            Category = 2,
                            Description = "Celular Samsung Galaxy A14 128GB Black",
                            Discount = 33,
                            Name = "Celular Samsung",
                            Price = 239999m
                        },
                        new
                        {
                            ProductId = new Guid("38f8f4bb-fd25-46ed-bafb-cf49a185c4cc"),
                            Category = 2,
                            Description = "Celular Xiaomi Redmi Note 11 128GB Negro",
                            Discount = 0,
                            Name = "Celular Xiaomi",
                            Price = 339999m
                        },
                        new
                        {
                            ProductId = new Guid("f97be315-939b-4334-8613-cadfc89cfa88"),
                            Category = 2,
                            Description = "Notebook Lenovo IdeaPad 1 14 pulgadas Intel Celeron 4GB 128GB SSD 82V60027AR",
                            Discount = 14,
                            Name = "Notebook Lenovo",
                            Price = 699999m
                        },
                        new
                        {
                            ProductId = new Guid("0b2824cf-8391-41ff-8cd1-398ffeee809d"),
                            Category = 2,
                            Description = "Impresora Multifunción HP Deskjet 2775",
                            Discount = 10,
                            Name = "Impresora multifuncion",
                            Price = 189999m
                        },
                        new
                        {
                            ProductId = new Guid("7caf1c58-e3bd-48b0-b08f-f314a2b6b632"),
                            Category = 3,
                            Description = "Campera canguro ride",
                            Discount = 0,
                            Name = "Campera",
                            Price = 51999m
                        },
                        new
                        {
                            ProductId = new Guid("9fd3b5db-52cf-4893-ab5c-22473523755c"),
                            Category = 3,
                            Description = "Buzo Anorak new fit",
                            Discount = 45,
                            Name = "Buzo",
                            Price = 43999m
                        },
                        new
                        {
                            ProductId = new Guid("7d3a0085-6ed1-4a3f-9dad-7ae728134ca4"),
                            Category = 3,
                            Description = "Bufanda de lana estampada desflecada",
                            Discount = 0,
                            Name = "Bufanda",
                            Price = 3500m
                        },
                        new
                        {
                            ProductId = new Guid("15bb89aa-5e21-4a40-af1f-6f46b27232b1"),
                            Category = 3,
                            Description = "Cartera / Bandolera importada rígida matelasse soft cuadrado con doble broche imantado.  Manija corta fija y manija larga desmontable y regulable.",
                            Discount = 5,
                            Name = "Cartera",
                            Price = 12500m
                        },
                        new
                        {
                            ProductId = new Guid("1f2dcca4-2e8c-4254-8d19-2349177b5c27"),
                            Category = 4,
                            Description = "Combo 4 Silla de Comedor Eames Home",
                            Discount = 30,
                            Name = "Sillas de comedor",
                            Price = 163017m
                        },
                        new
                        {
                            ProductId = new Guid("2c09e78a-c519-461e-ba36-904ada2ac255"),
                            Category = 4,
                            Description = "Sillón Individual escandinavo CH25 Hansen",
                            Discount = 25,
                            Name = "Sillon individual",
                            Price = 971285m
                        },
                        new
                        {
                            ProductId = new Guid("95c53e4a-516a-4040-919c-c0a9b0cd88eb"),
                            Category = 4,
                            Description = "Mesa de Comedor Thora",
                            Discount = 30,
                            Name = "Mesa",
                            Price = 970697m
                        },
                        new
                        {
                            ProductId = new Guid("8c969cf1-1fe7-4cfb-93a7-833f91503138"),
                            Category = 4,
                            Description = "Juego de Living de 3 Sillones + Mesa Salerno",
                            Discount = 25,
                            Name = "Juego de living",
                            Price = 2881015m
                        },
                        new
                        {
                            ProductId = new Guid("7c2b4f7a-af1b-4639-8e5c-1fe0ff856e01"),
                            Category = 5,
                            Description = "Kit doble de limpieza para pieles grasas libra niacinamida",
                            Discount = 0,
                            Name = "Kit de limpieza",
                            Price = 18697m
                        },
                        new
                        {
                            ProductId = new Guid("f64d44cc-acce-4f55-bbf8-5504e54035fd"),
                            Category = 5,
                            Description = "Kit Regulacion Piel Cabelluda Mixta/grasa( Incluye Neceser + Instructivo de uso)",
                            Discount = 13,
                            Name = "Kit para piel cabelluda",
                            Price = 36600m
                        },
                        new
                        {
                            ProductId = new Guid("d84e6c21-48e3-413f-b71b-7fe211b09491"),
                            Category = 5,
                            Description = "Serum bifasico revitalizante con niacinamida y agua de rosas",
                            Discount = 0,
                            Name = "Serum bifasico",
                            Price = 5000m
                        },
                        new
                        {
                            ProductId = new Guid("1e15d0c2-b910-46ba-9b0c-02fd53c6f541"),
                            Category = 5,
                            Description = "Suero hialuronico + niacinamida marca Libra Cosmetica",
                            Discount = 0,
                            Name = "Suero hialuronico",
                            Price = 6752m
                        },
                        new
                        {
                            ProductId = new Guid("391766d3-4325-445a-9b39-026ded74be4b"),
                            Category = 6,
                            Description = "Zapatillas deportivas de entrenamiento Topper Squat",
                            Discount = 12,
                            Name = "Zapatillas Deportivas",
                            Price = 50000m
                        },
                        new
                        {
                            ProductId = new Guid("89059776-1f9c-4796-87d9-3ae374aafa9b"),
                            Category = 6,
                            Description = "Shorts Alfest - futbol, running, basquet, gimnasio",
                            Discount = 0,
                            Name = "Shorts deportivos",
                            Price = 4440m
                        },
                        new
                        {
                            ProductId = new Guid("fb4eef76-0af4-4918-b160-1ac9c5aa451d"),
                            Category = 6,
                            Description = "Bestway 61052 bote inflable viaje/ocio",
                            Discount = 10,
                            Name = "Bote inflable",
                            Price = 21880m
                        },
                        new
                        {
                            ProductId = new Guid("07839859-d1a4-44ff-b343-0346dfa42264"),
                            Category = 6,
                            Description = "Tabla de surf 5.10 A 6.4 Stickwave",
                            Discount = 20,
                            Name = "Tabla de surf",
                            Price = 863000m
                        },
                        new
                        {
                            ProductId = new Guid("02d4f455-ba93-4336-8571-e1eb2fee92fd"),
                            Category = 7,
                            Description = "Jenga de mesa 54 piezas Wiss Toy",
                            Discount = 0,
                            Name = "Jenga",
                            Price = 9900m
                        },
                        new
                        {
                            ProductId = new Guid("371bdb06-92b7-489e-a0c1-d20208ab9803"),
                            Category = 7,
                            Description = "Set policia super realista, 6 piezas  con helicoptero - 10909",
                            Discount = 10,
                            Name = "Set de policia",
                            Price = 5520m
                        },
                        new
                        {
                            ProductId = new Guid("28f5e769-b739-416d-9747-55c36627b623"),
                            Category = 7,
                            Description = "Momodisk - Juego de encastre gigante de 25 piezas",
                            Discount = 15,
                            Name = "Juego de encastre",
                            Price = 48500m
                        },
                        new
                        {
                            ProductId = new Guid("db017c55-337d-421d-b664-b5f6ecdef2a1"),
                            Category = 7,
                            Description = "Camion militar desarmable de juguete con herramientas",
                            Discount = 0,
                            Name = "Camion de juguete",
                            Price = 2400m
                        },
                        new
                        {
                            ProductId = new Guid("5ebd65fe-f635-4871-aeab-7279c0929b06"),
                            Category = 8,
                            Description = "Leche entera larga vida Veronica Tetra x 1Lt",
                            Discount = 0,
                            Name = "Leche entera",
                            Price = 478m
                        },
                        new
                        {
                            ProductId = new Guid("e76b68f6-306f-40fe-9c57-2d06278c5475"),
                            Category = 8,
                            Description = "Coca-Cola original, gaseosa sabor cola",
                            Discount = 0,
                            Name = "Coca-Cola",
                            Price = 2900m
                        },
                        new
                        {
                            ProductId = new Guid("b38950e7-4b9d-4ab0-b3d8-1b3524cedd1c"),
                            Category = 8,
                            Description = "Pure de tomate Noel Brick x 520 Gr",
                            Discount = 0,
                            Name = "Pure de tomate",
                            Price = 970m
                        },
                        new
                        {
                            ProductId = new Guid("f937abb5-4360-4abc-a3b7-12438e30deee"),
                            Category = 8,
                            Description = "Jugo en polvo Arcor Naranja dulce 18 Gr",
                            Discount = 0,
                            Name = "Jugo en polvo",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = new Guid("fc98de65-1b25-42a8-aae5-143a6e102def"),
                            Category = 9,
                            Description = "Libro 'Redes de computadoras' de Andrew S. Tanenbaum Nva Edicion",
                            Discount = 0,
                            Name = "Redes de computadoras",
                            Price = 58000m
                        },
                        new
                        {
                            ProductId = new Guid("190db97f-b960-4131-8f85-4eaf7dff705f"),
                            Category = 9,
                            Description = "Libro 'Netter flashcards de anatomia: miembros' de John Hansen ",
                            Discount = 0,
                            Name = "Flashcards de anatomia",
                            Price = 40153m
                        },
                        new
                        {
                            ProductId = new Guid("fb67ac6b-2b6f-4dd7-82ec-4bf771b7292a"),
                            Category = 9,
                            Description = "coleccion El señor de los anillos - Tolkien - Set x 3 libros",
                            Discount = 10,
                            Name = "El señor de los anillos",
                            Price = 39900m
                        },
                        new
                        {
                            ProductId = new Guid("d3a10f54-d5bb-408c-9b9a-4efda318e953"),
                            Category = 9,
                            Description = "Saga de libros Dune 1-6 - Frank Herbert",
                            Discount = 14,
                            Name = "Dune",
                            Price = 109000m
                        },
                        new
                        {
                            ProductId = new Guid("38cdec18-ace9-412e-ab66-41294cb32161"),
                            Category = 10,
                            Description = "Kit de herramientas de jardineria Acero inoxidable C/bolsa",
                            Discount = 30,
                            Name = "Kit de jardineria",
                            Price = 398689m
                        },
                        new
                        {
                            ProductId = new Guid("272d2a15-bbec-490f-bc43-f43dd28df9ba"),
                            Category = 10,
                            Description = "Pulverizador fumigador para jardineria 2l Harden",
                            Discount = 0,
                            Name = "Fumigador",
                            Price = 2388m
                        },
                        new
                        {
                            ProductId = new Guid("bfc2103b-35b9-4ccc-b550-e7a61361905e"),
                            Category = 10,
                            Description = "Kit de herramientas de bricolaje para el hogar 25 piezas",
                            Discount = 15,
                            Name = "Kit de bricolaje",
                            Price = 138460m
                        },
                        new
                        {
                            ProductId = new Guid("5dde8e96-04d7-4b78-b9bc-34d318f1143a"),
                            Category = 10,
                            Description = "Kit de fabricacion de mldes de silicona AB 1:1 para bricolaje",
                            Discount = 0,
                            Name = "Kit de silicona",
                            Price = 13886m
                        });
                });

            modelBuilder.Entity("D_Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("D_Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCardId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("D_Domain.Entities.Product", b =>
                {
                    b.HasOne("D_Domain.Entities.Category", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("D_Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("D_Domain.Entities.Product", "IndividualProduct")
                        .WithMany("SalesProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_Domain.Entities.Sale", "IndividualSale")
                        .WithMany("SalesProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualProduct");

                    b.Navigation("IndividualSale");
                });

            modelBuilder.Entity("D_Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("D_Domain.Entities.Product", b =>
                {
                    b.Navigation("SalesProducts");
                });

            modelBuilder.Entity("D_Domain.Entities.Sale", b =>
                {
                    b.Navigation("SalesProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
