// <auto-generated />
using System;
using B_Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B_Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240419005714_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("D_Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electrodomésticos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Tecnología y Electrónica"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Moda y Accesorios"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hogar y Decoración"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Salud y Belleza"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Deportes y Ocio"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Juguetes y Juegos"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Alimentos y Bebidas"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Libros y Material Educativo"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Jardineriay Bricolaje"
                        });
                });

            modelBuilder.Entity("D_Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("Category");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("674ebfa7-0e26-443e-b4af-f45e5fd62f5b"),
                            Category = 1,
                            Description = "Heladera con freezer Marca Dream Hdr280f00b blanca clase A",
                            Discount = 17,
                            Name = "Heladera con freezer",
                            Price = 632798m
                        },
                        new
                        {
                            ProductId = new Guid("e1c3a8b7-e1a3-47f0-a576-0e9cf84c7212"),
                            Category = 1,
                            Description = "Aire acondicionado split frio/calor Carrier XPower 5120W 4400F 53HVG1801E",
                            Discount = 0,
                            Name = "Aire acondicionado",
                            Price = 1199999m
                        },
                        new
                        {
                            ProductId = new Guid("bf17ca72-e467-49a9-8fd3-faec0be8e176"),
                            Category = 1,
                            Description = "Smart TV 32 pulgadas HD Android TV Admiral AD32E3A",
                            Discount = 30,
                            Name = "Smart TV",
                            Price = 199999m
                        },
                        new
                        {
                            ProductId = new Guid("f6ef8035-7b6e-4c35-a472-6d7938e20ef9"),
                            Category = 1,
                            Description = "Lavaropas carga frontal 6kg 800 RPM Drean Next 6.08 ECO",
                            Discount = 24,
                            Name = "Lavaropas Carga Frontal",
                            Price = 669999m
                        },
                        new
                        {
                            ProductId = new Guid("40fac4fd-909f-4061-ad7c-7ce74a9cafab"),
                            Category = 2,
                            Description = "Celular Samsung Galaxy A14 128GB Black",
                            Discount = 33,
                            Name = "Celular Samsung",
                            Price = 239999m
                        },
                        new
                        {
                            ProductId = new Guid("0082469e-6f92-4139-9c30-0b3c486ea6dc"),
                            Category = 2,
                            Description = "Celular Xiaomi Redmi Note 11 128GB Negro",
                            Discount = 0,
                            Name = "Celular Xiaomi",
                            Price = 339999m
                        },
                        new
                        {
                            ProductId = new Guid("6d3007ff-32da-4b5f-b32b-b766405c12dd"),
                            Category = 2,
                            Description = "Notebook Lenovo IdeaPad 1 14 pulgadas Intel Celeron 4GB 128GB SSD 82V60027AR",
                            Discount = 14,
                            Name = "Notebook Lenovo",
                            Price = 699999m
                        },
                        new
                        {
                            ProductId = new Guid("ca0d9435-2f57-489b-8bff-459e6e2dc092"),
                            Category = 2,
                            Description = "Impresora Multifunción HP Deskjet 2775",
                            Discount = 10,
                            Name = "Impresora multifuncion",
                            Price = 189999m
                        },
                        new
                        {
                            ProductId = new Guid("f7fe379d-aea7-4489-a7c4-e15ae403b793"),
                            Category = 3,
                            Description = "Campera canguro ride",
                            Discount = 0,
                            Name = "Campera",
                            Price = 51999m
                        },
                        new
                        {
                            ProductId = new Guid("ab87f527-8161-4cf9-9eef-87cf760319c6"),
                            Category = 3,
                            Description = "Buzo Anorak new fit",
                            Discount = 45,
                            Name = "Buzo",
                            Price = 43999m
                        },
                        new
                        {
                            ProductId = new Guid("c5fe47b5-e502-46f3-a052-455bd3913f56"),
                            Category = 3,
                            Description = "Bufanda de lana estampada desflecada",
                            Discount = 0,
                            Name = "Bufanda",
                            Price = 3500m
                        },
                        new
                        {
                            ProductId = new Guid("62c3041a-a7d0-4f23-86e1-550c5f504d0c"),
                            Category = 3,
                            Description = "Cartera / Bandolera importada rígida matelasse soft cuadrado con doble broche imantado.  Manija corta fija y manija larga desmontable y regulable.",
                            Discount = 5,
                            Name = "Cartera",
                            Price = 12500m
                        },
                        new
                        {
                            ProductId = new Guid("87b6b5dc-cca4-4ff0-ba27-fd7a2ca60f91"),
                            Category = 4,
                            Description = "Combo 4 Silla de Comedor Eames Home",
                            Discount = 30,
                            Name = "Sillas de comedor",
                            Price = 163017m
                        },
                        new
                        {
                            ProductId = new Guid("86326528-3e67-475d-a014-64e7f59e1a10"),
                            Category = 4,
                            Description = "Sillón Individual escandinavo CH25 Hansen",
                            Discount = 25,
                            Name = "Sillon individual",
                            Price = 971285m
                        },
                        new
                        {
                            ProductId = new Guid("55bd8d63-244b-4712-80c9-9e2da6c39516"),
                            Category = 4,
                            Description = "Mesa de Comedor Thora",
                            Discount = 30,
                            Name = "Mesa",
                            Price = 970697m
                        },
                        new
                        {
                            ProductId = new Guid("5bd32ad0-afdc-4166-91ce-66bfd70cde53"),
                            Category = 4,
                            Description = "Juego de Living de 3 Sillones + Mesa Salerno",
                            Discount = 25,
                            Name = "Juego de living",
                            Price = 2881015m
                        },
                        new
                        {
                            ProductId = new Guid("e13e16ef-b638-40d1-bbad-36048bdf905e"),
                            Category = 5,
                            Description = "Kit doble de limpieza para pieles grasas libra niacinamida",
                            Discount = 0,
                            Name = "Kit de limpieza",
                            Price = 18697m
                        },
                        new
                        {
                            ProductId = new Guid("e4e16bd1-3ab6-4871-8c52-fe6b4ca24c24"),
                            Category = 5,
                            Description = "Kit Regulacion Piel Cabelluda Mixta/grasa( Incluye Neceser + Instructivo de uso)",
                            Discount = 13,
                            Name = "Kit para piel cabelluda",
                            Price = 36600m
                        },
                        new
                        {
                            ProductId = new Guid("57bbd1e2-d068-4745-9b83-02c5a6670d66"),
                            Category = 5,
                            Description = "Serum bifasico revitalizante con niacinamida y agua de rosas",
                            Discount = 0,
                            Name = "Serum bifasico",
                            Price = 5000m
                        },
                        new
                        {
                            ProductId = new Guid("72945199-3f8c-4257-abab-1f01ada8d0ba"),
                            Category = 5,
                            Description = "Suero hialuronico + niacinamida marca Libra Cosmetica",
                            Discount = 0,
                            Name = "Suero hialuronico",
                            Price = 6752m
                        },
                        new
                        {
                            ProductId = new Guid("51496559-9837-4336-ac9c-e0ed009a3008"),
                            Category = 6,
                            Description = "Zapatillas deportivas de entrenamiento Topper Squat",
                            Discount = 12,
                            Name = "Zapatillas Deportivas",
                            Price = 50000m
                        },
                        new
                        {
                            ProductId = new Guid("b7eb07d1-b639-48f6-a01d-4b039fc0c3c6"),
                            Category = 6,
                            Description = "Shorts Alfest - futbol, running, basquet, gimnasio",
                            Discount = 0,
                            Name = "Shorts deportivos",
                            Price = 4440m
                        },
                        new
                        {
                            ProductId = new Guid("949a745a-6aa3-4032-a1e3-4b2476fe363f"),
                            Category = 6,
                            Description = "Bestway 61052 bote inflable viaje/ocio",
                            Discount = 10,
                            Name = "Bote inflable",
                            Price = 21880m
                        },
                        new
                        {
                            ProductId = new Guid("570bcbc5-9a90-4fbe-a97b-b68bd570cccd"),
                            Category = 6,
                            Description = "Tabla de surf 5.10 A 6.4 Stickwave",
                            Discount = 20,
                            Name = "Tabla de surf",
                            Price = 863000m
                        },
                        new
                        {
                            ProductId = new Guid("fcb507a7-2906-4d12-8661-603ff39121d8"),
                            Category = 7,
                            Description = "Jenga de mesa 54 piezas Wiss Toy",
                            Discount = 0,
                            Name = "Jenga",
                            Price = 9900m
                        },
                        new
                        {
                            ProductId = new Guid("1207b83b-6f3d-4cc9-a3d4-d0a17ed490de"),
                            Category = 7,
                            Description = "Set policia super realista, 6 piezas  con helicoptero - 10909",
                            Discount = 10,
                            Name = "Set de policia",
                            Price = 5520m
                        },
                        new
                        {
                            ProductId = new Guid("8d8c6de2-2c43-474b-917b-4d6e4953ac06"),
                            Category = 7,
                            Description = "Momodisk - Juego de encastre gigante de 25 piezas",
                            Discount = 15,
                            Name = "Juego de encastre",
                            Price = 48500m
                        },
                        new
                        {
                            ProductId = new Guid("5025d569-dfa4-4699-b9bd-b10b8013788f"),
                            Category = 7,
                            Description = "Camion militar desarmable de juguete con herramientas",
                            Discount = 0,
                            Name = "Camion de juguete",
                            Price = 2400m
                        },
                        new
                        {
                            ProductId = new Guid("a15ac31c-a7ad-42c9-87d4-7155b8f4cf4f"),
                            Category = 8,
                            Description = "Leche entera larga vida Veronica Tetra x 1Lt",
                            Discount = 0,
                            Name = "Leche entera",
                            Price = 478m
                        },
                        new
                        {
                            ProductId = new Guid("cb99267a-26b1-4b9b-93ff-30bff3081808"),
                            Category = 8,
                            Description = "Coca-Cola original, gaseosa sabor cola",
                            Discount = 0,
                            Name = "Coca-Cola",
                            Price = 2900m
                        },
                        new
                        {
                            ProductId = new Guid("d97fe8a2-1d6f-4ea3-ad45-c39f3f90cfa0"),
                            Category = 8,
                            Description = "Pure de tomate Noel Brick x 520 Gr",
                            Discount = 0,
                            Name = "Pure de tomate",
                            Price = 970m
                        },
                        new
                        {
                            ProductId = new Guid("377314d2-9780-41c3-907e-acc74ac35edf"),
                            Category = 8,
                            Description = "Jugo en polvo Arcor Naranja dulce 18 Gr",
                            Discount = 0,
                            Name = "Jugo en polvo",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = new Guid("acfacd42-a98e-462a-a3a8-6fe05991cbe2"),
                            Category = 9,
                            Description = "Libro 'Redes de computadoras' de Andrew S. Tanenbaum Nva Edicion",
                            Discount = 0,
                            Name = "Redes de computadoras",
                            Price = 58000m
                        },
                        new
                        {
                            ProductId = new Guid("bdd61dc0-1b64-4f77-a9f1-728e9299d18a"),
                            Category = 9,
                            Description = "Libro 'Netter flashcards de anatomia: miembros' de John Hansen ",
                            Discount = 0,
                            Name = "Flashcards de anatomia",
                            Price = 40153m
                        },
                        new
                        {
                            ProductId = new Guid("c1c004c0-7fbe-4757-a3e2-c4f61f13520a"),
                            Category = 9,
                            Description = "coleccion El señor de los anillos - Tolkien - Set x 3 libros",
                            Discount = 10,
                            Name = "El señor de los anillos",
                            Price = 39900m
                        },
                        new
                        {
                            ProductId = new Guid("6f2e5e5f-bab1-4d82-a408-fedd145a0c96"),
                            Category = 9,
                            Description = "Saga de libros Dune 1-6 - Frank Herbert",
                            Discount = 14,
                            Name = "Dune",
                            Price = 109000m
                        },
                        new
                        {
                            ProductId = new Guid("b020fa0a-5492-4ba5-ab13-f6051e24e0ba"),
                            Category = 10,
                            Description = "Kit de herramientas de jardineria Acero inoxidable C/bolsa",
                            Discount = 30,
                            Name = "Kit de jardineria",
                            Price = 398689m
                        },
                        new
                        {
                            ProductId = new Guid("872220da-b547-4567-bfad-0315377c18c7"),
                            Category = 10,
                            Description = "Pulverizador fumigador para jardineria 2l Harden",
                            Discount = 0,
                            Name = "Fumigador",
                            Price = 2388m
                        },
                        new
                        {
                            ProductId = new Guid("39fb84cd-fdfc-4ce8-9ae5-95f9b12e3fb9"),
                            Category = 10,
                            Description = "Kit de herramientas de bricolaje para el hogar 25 piezas",
                            Discount = 15,
                            Name = "Kit de bricolaje",
                            Price = 138460m
                        },
                        new
                        {
                            ProductId = new Guid("34ae22ca-a950-42e8-8c2a-55733aab344b"),
                            Category = 10,
                            Description = "Kit de fabricacion de mldes de silicona AB 1:1 para bricolaje",
                            Discount = 0,
                            Name = "Kit de silicona",
                            Price = 13886m
                        });
                });

            modelBuilder.Entity("D_Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale", (string)null);
                });

            modelBuilder.Entity("D_Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("ShoppingCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCardId"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Product")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCardId");

                    b.HasIndex("Product");

                    b.HasIndex("Sale");

                    b.ToTable("SaleProduct", (string)null);
                });

            modelBuilder.Entity("D_Domain.Entities.Product", b =>
                {
                    b.HasOne("D_Domain.Entities.Category", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("D_Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("D_Domain.Entities.Product", "IndividualProduct")
                        .WithMany("SalesProducts")
                        .HasForeignKey("Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("D_Domain.Entities.Sale", "IndividualSale")
                        .WithMany("SalesProducts")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualProduct");

                    b.Navigation("IndividualSale");
                });

            modelBuilder.Entity("D_Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("D_Domain.Entities.Product", b =>
                {
                    b.Navigation("SalesProducts");
                });

            modelBuilder.Entity("D_Domain.Entities.Sale", b =>
                {
                    b.Navigation("SalesProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
